version: '2'
services:
    istart-app:
        image: istart
        external_links:
            - istart-mysql:mysql
            - istart-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/istart?useUnicode=true&characterEncoding=utf8&useSSL=false
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    istart-mysql:
        extends:
            file: mysql.yml
            service: istart-mysql
    istart-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: istart-elasticsearch
